// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package plain

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

type BooleanInput struct {
	Value bool `json:"value"`
}

// GetValue returns BooleanInput.Value, and is useful for accessing the field via an interface.
func (v *BooleanInput) GetValue() bool { return v.Value }

// Input for a single step in the bulk upsert operation.
type BulkUpsertWorkflowStepInput struct {
	// Optional step ID - if provided and exists in this workflow, step will be updated. Otherwise created with new ID.
	StepId *string `json:"stepId"`
	// The type of step: CONDITION or ACTION.
	Type WorkflowStepType `json:"type"`
	// Optional name for the step.
	Name *string `json:"name"`
	// JSON-encoded payload containing the action or condition configuration. See `WorkflowStep.payload` for the valid `type` values per step type and the note on non-portable, workspace-specific IDs.
	Payload string `json:"payload"`
	// Transition step IDs. ACTION steps: [nextStepId], CONDITION steps: [trueStepId, falseStepId]. Use null for terminal/no branch.
	Transitions []*string `json:"transitions"`
	// X position of this step on the canvas.
	PositionX *float64 `json:"positionX"`
	// Y position of this step on the canvas.
	PositionY *float64 `json:"positionY"`
}

// GetStepId returns BulkUpsertWorkflowStepInput.StepId, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetStepId() *string { return v.StepId }

// GetType returns BulkUpsertWorkflowStepInput.Type, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetType() WorkflowStepType { return v.Type }

// GetName returns BulkUpsertWorkflowStepInput.Name, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetName() *string { return v.Name }

// GetPayload returns BulkUpsertWorkflowStepInput.Payload, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetPayload() string { return v.Payload }

// GetTransitions returns BulkUpsertWorkflowStepInput.Transitions, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetTransitions() []*string { return v.Transitions }

// GetPositionX returns BulkUpsertWorkflowStepInput.PositionX, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetPositionX() *float64 { return v.PositionX }

// GetPositionY returns BulkUpsertWorkflowStepInput.PositionY, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepInput) GetPositionY() *float64 { return v.PositionY }

type BulkUpsertWorkflowStepResult string

const (
	BulkUpsertWorkflowStepResultCreated BulkUpsertWorkflowStepResult = "CREATED"
	BulkUpsertWorkflowStepResultUpdated BulkUpsertWorkflowStepResult = "UPDATED"
	BulkUpsertWorkflowStepResultNoop    BulkUpsertWorkflowStepResult = "NOOP"
)

var AllBulkUpsertWorkflowStepResult = []BulkUpsertWorkflowStepResult{
	BulkUpsertWorkflowStepResultCreated,
	BulkUpsertWorkflowStepResultUpdated,
	BulkUpsertWorkflowStepResultNoop,
}

// BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput includes the requested fields of the GraphQL type BulkUpsertWorkflowStepsOutput.
type BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput struct {
	// Results for each step in the input (same order as input).
	Results []*BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem `json:"results"`
	Error   *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError                        `json:"error"`
}

// GetResults returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput.Results, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput) GetResults() []*BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem {
	return v.Results
}

// GetError returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput.Error, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput) GetError() *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError {
	return v.Error
}

// BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// A type indicating an error has occurred while making a mutation.
type BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError struct {
	MutationErrorFields `json:"-"`
}

// GetMessage returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) GetMessage() string {
	return v.MutationErrorFields.Message
}

// GetType returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError.Type, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) GetType() MutationErrorType {
	return v.MutationErrorFields.Type
}

// GetCode returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError.Code, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) GetCode() string {
	return v.MutationErrorFields.Code
}

// GetFields returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError.Fields, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) GetFields() []*MutationErrorFieldsFieldsMutationFieldError {
	return v.MutationErrorFields.Fields
}

func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError
		graphql.NoUnmarshalJSON
	}
	firstPass.BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.MutationErrorFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError struct {
	Message string `json:"message"`

	Type MutationErrorType `json:"type"`

	Code string `json:"code"`

	Fields []*MutationErrorFieldsFieldsMutationFieldError `json:"fields"`
}

func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError) __premarshalJSON() (*__premarshalBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError, error) {
	var retval __premarshalBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputErrorMutationError

	retval.Message = v.MutationErrorFields.Message
	retval.Type = v.MutationErrorFields.Type
	retval.Code = v.MutationErrorFields.Code
	retval.Fields = v.MutationErrorFields.Fields
	return &retval, nil
}

// BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem includes the requested fields of the GraphQL type BulkUpsertWorkflowStepResultItem.
type BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem struct {
	Result       BulkUpsertWorkflowStepResult                                                                                                    `json:"result"`
	WorkflowStep *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep `json:"workflowStep"`
}

// GetResult returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem.Result, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem) GetResult() BulkUpsertWorkflowStepResult {
	return v.Result
}

// GetWorkflowStep returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem.WorkflowStep, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItem) GetWorkflowStep() *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep {
	return v.WorkflowStep
}

// BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep includes the requested fields of the GraphQL type WorkflowStep.
type BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep struct {
	WorkflowStepFields `json:"-"`
}

// GetId returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.Id, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetId() string {
	return v.WorkflowStepFields.Id
}

// GetWorkflowId returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.WorkflowId, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetWorkflowId() string {
	return v.WorkflowStepFields.WorkflowId
}

// GetType returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.Type, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetType() WorkflowStepType {
	return v.WorkflowStepFields.Type
}

// GetName returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.Name, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetName() *string {
	return v.WorkflowStepFields.Name
}

// GetPayload returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.Payload, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetPayload() string {
	return v.WorkflowStepFields.Payload
}

// GetTransitions returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.Transitions, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetTransitions() []*string {
	return v.WorkflowStepFields.Transitions
}

// GetPositionX returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.PositionX, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetPositionX() float64 {
	return v.WorkflowStepFields.PositionX
}

// GetPositionY returns BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep.PositionY, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) GetPositionY() float64 {
	return v.WorkflowStepFields.PositionY
}

func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep
		graphql.NoUnmarshalJSON
	}
	firstPass.BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.WorkflowStepFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep struct {
	Id string `json:"id"`

	WorkflowId string `json:"workflowId"`

	Type WorkflowStepType `json:"type"`

	Name *string `json:"name"`

	Payload string `json:"payload"`

	Transitions []*string `json:"transitions"`

	PositionX float64 `json:"positionX"`

	PositionY float64 `json:"positionY"`
}

func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep) __premarshalJSON() (*__premarshalBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep, error) {
	var retval __premarshalBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutputResultsBulkUpsertWorkflowStepResultItemWorkflowStep

	retval.Id = v.WorkflowStepFields.Id
	retval.WorkflowId = v.WorkflowStepFields.WorkflowId
	retval.Type = v.WorkflowStepFields.Type
	retval.Name = v.WorkflowStepFields.Name
	retval.Payload = v.WorkflowStepFields.Payload
	retval.Transitions = v.WorkflowStepFields.Transitions
	retval.PositionX = v.WorkflowStepFields.PositionX
	retval.PositionY = v.WorkflowStepFields.PositionY
	return &retval, nil
}

type BulkUpsertWorkflowStepsInput struct {
	WorkflowId string `json:"workflowId"`
	// The complete list of steps. Steps with existing IDs are updated, new IDs are created, missing IDs are deleted.
	Steps []*BulkUpsertWorkflowStepInput `json:"steps,omitempty"`
	// Optional: Set this as the workflow's startStepId. Use null to clear. If not provided, startStepId is unchanged. Clearing to null fails on a published workflow — unpublish before restructuring, then republish.
	StartStepId *string `json:"startStepId"`
	// Optional: JSON-encoded trigger configuration. If not provided, trigger is unchanged. See `Workflow.trigger` for the valid `type` values and their required fields.
	Trigger *StringInput `json:"trigger,omitempty"`
}

// GetWorkflowId returns BulkUpsertWorkflowStepsInput.WorkflowId, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsInput) GetWorkflowId() string { return v.WorkflowId }

// GetSteps returns BulkUpsertWorkflowStepsInput.Steps, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsInput) GetSteps() []*BulkUpsertWorkflowStepInput { return v.Steps }

// GetStartStepId returns BulkUpsertWorkflowStepsInput.StartStepId, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsInput) GetStartStepId() *string { return v.StartStepId }

// GetTrigger returns BulkUpsertWorkflowStepsInput.Trigger, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsInput) GetTrigger() *StringInput { return v.Trigger }

// BulkUpsertWorkflowStepsResponse is returned by BulkUpsertWorkflowSteps on success.
type BulkUpsertWorkflowStepsResponse struct {
	// Atomically replace all steps in a workflow. Steps with a matching `stepId` are updated; steps without an ID (or with a new ID) are created; steps that existed before but are absent from the input are deleted.
	// Optionally updates `startStepId` and the trigger configuration in the same call. Maximum 60 steps per workflow.
	BulkUpsertWorkflowSteps *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput `json:"bulkUpsertWorkflowSteps"`
}

// GetBulkUpsertWorkflowSteps returns BulkUpsertWorkflowStepsResponse.BulkUpsertWorkflowSteps, and is useful for accessing the field via an interface.
func (v *BulkUpsertWorkflowStepsResponse) GetBulkUpsertWorkflowSteps() *BulkUpsertWorkflowStepsBulkUpsertWorkflowStepsBulkUpsertWorkflowStepsOutput {
	return v.BulkUpsertWorkflowSteps
}

// CreateWorkflowCreateWorkflowCreateWorkflowOutput includes the requested fields of the GraphQL type CreateWorkflowOutput.
type CreateWorkflowCreateWorkflowCreateWorkflowOutput struct {
	Workflow *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow           `json:"workflow"`
	Error    *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError `json:"error"`
}

// GetWorkflow returns CreateWorkflowCreateWorkflowCreateWorkflowOutput.Workflow, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutput) GetWorkflow() *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow {
	return v.Workflow
}

// GetError returns CreateWorkflowCreateWorkflowCreateWorkflowOutput.Error, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutput) GetError() *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError {
	return v.Error
}

// CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// A type indicating an error has occurred while making a mutation.
type CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError struct {
	MutationErrorFields `json:"-"`
}

// GetMessage returns CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) GetMessage() string {
	return v.MutationErrorFields.Message
}

// GetType returns CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError.Type, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) GetType() MutationErrorType {
	return v.MutationErrorFields.Type
}

// GetCode returns CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError.Code, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) GetCode() string {
	return v.MutationErrorFields.Code
}

// GetFields returns CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError.Fields, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) GetFields() []*MutationErrorFieldsFieldsMutationFieldError {
	return v.MutationErrorFields.Fields
}

func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError
		graphql.NoUnmarshalJSON
	}
	firstPass.CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.MutationErrorFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalCreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError struct {
	Message string `json:"message"`

	Type MutationErrorType `json:"type"`

	Code string `json:"code"`

	Fields []*MutationErrorFieldsFieldsMutationFieldError `json:"fields"`
}

func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError) __premarshalJSON() (*__premarshalCreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError, error) {
	var retval __premarshalCreateWorkflowCreateWorkflowCreateWorkflowOutputErrorMutationError

	retval.Message = v.MutationErrorFields.Message
	retval.Type = v.MutationErrorFields.Type
	retval.Code = v.MutationErrorFields.Code
	retval.Fields = v.MutationErrorFields.Fields
	return &retval, nil
}

// CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow includes the requested fields of the GraphQL type Workflow.
type CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow struct {
	WorkflowFields `json:"-"`
}

// GetId returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.Id, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetId() string {
	return v.WorkflowFields.Id
}

// GetName returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.Name, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetName() string {
	return v.WorkflowFields.Name
}

// GetTrigger returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.Trigger, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetTrigger() string {
	return v.WorkflowFields.Trigger
}

// GetStartStepId returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.StartStepId, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetStartStepId() *string {
	return v.WorkflowFields.StartStepId
}

// GetPublishedAt returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.PublishedAt, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetPublishedAt() *WorkflowFieldsPublishedAtDateTime {
	return v.WorkflowFields.PublishedAt
}

// GetOrder returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.Order, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetOrder() int {
	return v.WorkflowFields.Order
}

// GetSteps returns CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow.Steps, and is useful for accessing the field via an interface.
func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) GetSteps() []*WorkflowFieldsStepsWorkflowStep {
	return v.WorkflowFields.Steps
}

func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow
		graphql.NoUnmarshalJSON
	}
	firstPass.CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.WorkflowFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalCreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Trigger string `json:"trigger"`

	StartStepId *string `json:"startStepId"`

	PublishedAt *WorkflowFieldsPublishedAtDateTime `json:"publishedAt"`

	Order int `json:"order"`

	Steps []*WorkflowFieldsStepsWorkflowStep `json:"steps"`
}

func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *CreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow) __premarshalJSON() (*__premarshalCreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow, error) {
	var retval __premarshalCreateWorkflowCreateWorkflowCreateWorkflowOutputWorkflow

	retval.Id = v.WorkflowFields.Id
	retval.Name = v.WorkflowFields.Name
	retval.Trigger = v.WorkflowFields.Trigger
	retval.StartStepId = v.WorkflowFields.StartStepId
	retval.PublishedAt = v.WorkflowFields.PublishedAt
	retval.Order = v.WorkflowFields.Order
	retval.Steps = v.WorkflowFields.Steps
	return &retval, nil
}

type CreateWorkflowInput struct {
	Name string `json:"name"`
	// JSON-encoded trigger configuration. See `Workflow.trigger` for the valid `type` values and their required fields.
	Trigger string `json:"trigger"`
	// The gallery template this workflow was created from, if any. Recorded once and never updated — the workflow diverges as soon as it is edited.
	SourceTemplateId *string `json:"sourceTemplateId"`
}

// GetName returns CreateWorkflowInput.Name, and is useful for accessing the field via an interface.
func (v *CreateWorkflowInput) GetName() string { return v.Name }

// GetTrigger returns CreateWorkflowInput.Trigger, and is useful for accessing the field via an interface.
func (v *CreateWorkflowInput) GetTrigger() string { return v.Trigger }

// GetSourceTemplateId returns CreateWorkflowInput.SourceTemplateId, and is useful for accessing the field via an interface.
func (v *CreateWorkflowInput) GetSourceTemplateId() *string { return v.SourceTemplateId }

// CreateWorkflowResponse is returned by CreateWorkflow on success.
type CreateWorkflowResponse struct {
	// Create a new workflow. The workflow starts unpublished with no steps; use `bulkUpsertWorkflowSteps` to add steps and `updateWorkflow` to publish it.
	// The `trigger` field must be a valid JSON-encoded trigger configuration.
	CreateWorkflow *CreateWorkflowCreateWorkflowCreateWorkflowOutput `json:"createWorkflow"`
}

// GetCreateWorkflow returns CreateWorkflowResponse.CreateWorkflow, and is useful for accessing the field via an interface.
func (v *CreateWorkflowResponse) GetCreateWorkflow() *CreateWorkflowCreateWorkflowCreateWorkflowOutput {
	return v.CreateWorkflow
}

// DeleteWorkflowDeleteWorkflowDeleteWorkflowOutput includes the requested fields of the GraphQL type DeleteWorkflowOutput.
type DeleteWorkflowDeleteWorkflowDeleteWorkflowOutput struct {
	Error *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError `json:"error"`
}

// GetError returns DeleteWorkflowDeleteWorkflowDeleteWorkflowOutput.Error, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutput) GetError() *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError {
	return v.Error
}

// DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// A type indicating an error has occurred while making a mutation.
type DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError struct {
	MutationErrorFields `json:"-"`
}

// GetMessage returns DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) GetMessage() string {
	return v.MutationErrorFields.Message
}

// GetType returns DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError.Type, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) GetType() MutationErrorType {
	return v.MutationErrorFields.Type
}

// GetCode returns DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError.Code, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) GetCode() string {
	return v.MutationErrorFields.Code
}

// GetFields returns DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError.Fields, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) GetFields() []*MutationErrorFieldsFieldsMutationFieldError {
	return v.MutationErrorFields.Fields
}

func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError
		graphql.NoUnmarshalJSON
	}
	firstPass.DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.MutationErrorFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalDeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError struct {
	Message string `json:"message"`

	Type MutationErrorType `json:"type"`

	Code string `json:"code"`

	Fields []*MutationErrorFieldsFieldsMutationFieldError `json:"fields"`
}

func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError) __premarshalJSON() (*__premarshalDeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError, error) {
	var retval __premarshalDeleteWorkflowDeleteWorkflowDeleteWorkflowOutputErrorMutationError

	retval.Message = v.MutationErrorFields.Message
	retval.Type = v.MutationErrorFields.Type
	retval.Code = v.MutationErrorFields.Code
	retval.Fields = v.MutationErrorFields.Fields
	return &retval, nil
}

type DeleteWorkflowInput struct {
	WorkflowId string `json:"workflowId"`
}

// GetWorkflowId returns DeleteWorkflowInput.WorkflowId, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowInput) GetWorkflowId() string { return v.WorkflowId }

// DeleteWorkflowResponse is returned by DeleteWorkflow on success.
type DeleteWorkflowResponse struct {
	// Permanently delete a workflow and all its steps. Existing executions are retained for audit purposes.
	DeleteWorkflow *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutput `json:"deleteWorkflow"`
}

// GetDeleteWorkflow returns DeleteWorkflowResponse.DeleteWorkflow, and is useful for accessing the field via an interface.
func (v *DeleteWorkflowResponse) GetDeleteWorkflow() *DeleteWorkflowDeleteWorkflowDeleteWorkflowOutput {
	return v.DeleteWorkflow
}

// GetWorkflowResponse is returned by GetWorkflow on success.
type GetWorkflowResponse struct {
	// Get a workflow by id. Returns null if no workflow with the given ID exists.
	// Workflows are the step-based automation model that supports conditions, actions, and wait steps connected in a graph.
	Workflow *GetWorkflowWorkflow `json:"workflow"`
}

// GetWorkflow returns GetWorkflowResponse.Workflow, and is useful for accessing the field via an interface.
func (v *GetWorkflowResponse) GetWorkflow() *GetWorkflowWorkflow { return v.Workflow }

// GetWorkflowWorkflow includes the requested fields of the GraphQL type Workflow.
type GetWorkflowWorkflow struct {
	WorkflowFields `json:"-"`
}

// GetId returns GetWorkflowWorkflow.Id, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetId() string { return v.WorkflowFields.Id }

// GetName returns GetWorkflowWorkflow.Name, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetName() string { return v.WorkflowFields.Name }

// GetTrigger returns GetWorkflowWorkflow.Trigger, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetTrigger() string { return v.WorkflowFields.Trigger }

// GetStartStepId returns GetWorkflowWorkflow.StartStepId, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetStartStepId() *string { return v.WorkflowFields.StartStepId }

// GetPublishedAt returns GetWorkflowWorkflow.PublishedAt, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetPublishedAt() *WorkflowFieldsPublishedAtDateTime {
	return v.WorkflowFields.PublishedAt
}

// GetOrder returns GetWorkflowWorkflow.Order, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetOrder() int { return v.WorkflowFields.Order }

// GetSteps returns GetWorkflowWorkflow.Steps, and is useful for accessing the field via an interface.
func (v *GetWorkflowWorkflow) GetSteps() []*WorkflowFieldsStepsWorkflowStep {
	return v.WorkflowFields.Steps
}

func (v *GetWorkflowWorkflow) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetWorkflowWorkflow
		graphql.NoUnmarshalJSON
	}
	firstPass.GetWorkflowWorkflow = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.WorkflowFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalGetWorkflowWorkflow struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Trigger string `json:"trigger"`

	StartStepId *string `json:"startStepId"`

	PublishedAt *WorkflowFieldsPublishedAtDateTime `json:"publishedAt"`

	Order int `json:"order"`

	Steps []*WorkflowFieldsStepsWorkflowStep `json:"steps"`
}

func (v *GetWorkflowWorkflow) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetWorkflowWorkflow) __premarshalJSON() (*__premarshalGetWorkflowWorkflow, error) {
	var retval __premarshalGetWorkflowWorkflow

	retval.Id = v.WorkflowFields.Id
	retval.Name = v.WorkflowFields.Name
	retval.Trigger = v.WorkflowFields.Trigger
	retval.StartStepId = v.WorkflowFields.StartStepId
	retval.PublishedAt = v.WorkflowFields.PublishedAt
	retval.Order = v.WorkflowFields.Order
	retval.Steps = v.WorkflowFields.Steps
	return &retval, nil
}

type IntInput struct {
	Value int `json:"value"`
}

// GetValue returns IntInput.Value, and is useful for accessing the field via an interface.
func (v *IntInput) GetValue() int { return v.Value }

// MutationErrorFields includes the GraphQL fields of MutationError requested by the fragment MutationErrorFields.
// The GraphQL type's documentation follows.
//
// A type indicating an error has occurred while making a mutation.
type MutationErrorFields struct {
	// An English technical description of the error. This error is usually meant to be read by a developer and not an end user.
	Message string `json:"message"`
	// The type of error. Can be used to display a user friendly error message.
	Type MutationErrorType `json:"type"`
	// A fixed error code that can be used to handle this error, see https://www.plain.com/docs/graphql/error-codes for a description of each code.
	Code string `json:"code"`
	// The array of fields that are impacted by this error.
	Fields []*MutationErrorFieldsFieldsMutationFieldError `json:"fields"`
}

// GetMessage returns MutationErrorFields.Message, and is useful for accessing the field via an interface.
func (v *MutationErrorFields) GetMessage() string { return v.Message }

// GetType returns MutationErrorFields.Type, and is useful for accessing the field via an interface.
func (v *MutationErrorFields) GetType() MutationErrorType { return v.Type }

// GetCode returns MutationErrorFields.Code, and is useful for accessing the field via an interface.
func (v *MutationErrorFields) GetCode() string { return v.Code }

// GetFields returns MutationErrorFields.Fields, and is useful for accessing the field via an interface.
func (v *MutationErrorFields) GetFields() []*MutationErrorFieldsFieldsMutationFieldError {
	return v.Fields
}

// MutationErrorFieldsFieldsMutationFieldError includes the requested fields of the GraphQL type MutationFieldError.
// The GraphQL type's documentation follows.
//
// A type indicating an error has occurred with a specific field in the input.
type MutationErrorFieldsFieldsMutationFieldError struct {
	// The name of the field for which the error happened.
	Field string `json:"field"`
	// An English technical description of the error. This error is usually meant to be read by a developer and not an end user.
	Message string `json:"message"`
	// The type of the error. Can be used to display a user friendly error message.
	Type MutationFieldErrorType `json:"type"`
}

// GetField returns MutationErrorFieldsFieldsMutationFieldError.Field, and is useful for accessing the field via an interface.
func (v *MutationErrorFieldsFieldsMutationFieldError) GetField() string { return v.Field }

// GetMessage returns MutationErrorFieldsFieldsMutationFieldError.Message, and is useful for accessing the field via an interface.
func (v *MutationErrorFieldsFieldsMutationFieldError) GetMessage() string { return v.Message }

// GetType returns MutationErrorFieldsFieldsMutationFieldError.Type, and is useful for accessing the field via an interface.
func (v *MutationErrorFieldsFieldsMutationFieldError) GetType() MutationFieldErrorType { return v.Type }

// An enum for why the mutation failed overall.
type MutationErrorType string

const (
	// Input validation failed, see the `fields` for details on why the input was invalid.
	MutationErrorTypeValidation MutationErrorType = "VALIDATION"
	// The user is not authorized to do this mutation. See `message` for details on which permissions are missing.
	MutationErrorTypeForbidden MutationErrorType = "FORBIDDEN"
	// An unknown internal server error occurred. Retry the mutation and if it persists, please email help@plain.com
	MutationErrorTypeInternal MutationErrorType = "INTERNAL"
)

var AllMutationErrorType = []MutationErrorType{
	MutationErrorTypeValidation,
	MutationErrorTypeForbidden,
	MutationErrorTypeInternal,
}

// An enum specific to each field, explaining why validation failed.
type MutationFieldErrorType string

const (
	// The field was provided, but didn't pass the requirements of the field. See `message` for details on why.
	MutationFieldErrorTypeValidation MutationFieldErrorType = "VALIDATION"
	// The field is required to be provided. String inputs may be trimmed and checked for emptiness.
	MutationFieldErrorTypeRequired MutationFieldErrorType = "REQUIRED"
	// The input field referenced an entity that wasn't found.
	MutationFieldErrorTypeNotFound MutationFieldErrorType = "NOT_FOUND"
)

var AllMutationFieldErrorType = []MutationFieldErrorType{
	MutationFieldErrorTypeValidation,
	MutationFieldErrorTypeRequired,
	MutationFieldErrorTypeNotFound,
}

type StringInput struct {
	Value string `json:"value"`
}

// GetValue returns StringInput.Value, and is useful for accessing the field via an interface.
func (v *StringInput) GetValue() string { return v.Value }

type UpdateWorkflowInput struct {
	WorkflowId string       `json:"workflowId"`
	Name       *StringInput `json:"name,omitempty"`
	// JSON-encoded trigger configuration. See `Workflow.trigger` for the valid `type` values and their required fields.
	Trigger *StringInput `json:"trigger,omitempty"`
	// The ID of the first step to execute. Cannot be cleared to null on a published workflow; unpublish (`isPublished: false`) before restructuring steps, then republish.
	StartStepId *StringInput  `json:"startStepId,omitempty"`
	Order       *IntInput     `json:"order,omitempty"`
	IsPublished *BooleanInput `json:"isPublished,omitempty"`
}

// GetWorkflowId returns UpdateWorkflowInput.WorkflowId, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowInput) GetWorkflowId() string { return v.WorkflowId }

// GetName returns UpdateWorkflowInput.Name, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowInput) GetName() *StringInput { return v.Name }

// GetTrigger returns UpdateWorkflowInput.Trigger, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowInput) GetTrigger() *StringInput { return v.Trigger }

// GetStartStepId returns UpdateWorkflowInput.StartStepId, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowInput) GetStartStepId() *StringInput { return v.StartStepId }

// GetOrder returns UpdateWorkflowInput.Order, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowInput) GetOrder() *IntInput { return v.Order }

// GetIsPublished returns UpdateWorkflowInput.IsPublished, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowInput) GetIsPublished() *BooleanInput { return v.IsPublished }

// UpdateWorkflowResponse is returned by UpdateWorkflow on success.
type UpdateWorkflowResponse struct {
	// Update a workflow's name, trigger configuration, entry step, display order, or published status.
	UpdateWorkflow *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput `json:"updateWorkflow"`
}

// GetUpdateWorkflow returns UpdateWorkflowResponse.UpdateWorkflow, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowResponse) GetUpdateWorkflow() *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput {
	return v.UpdateWorkflow
}

// UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput includes the requested fields of the GraphQL type UpdateWorkflowOutput.
type UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput struct {
	Workflow *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow           `json:"workflow"`
	Error    *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError `json:"error"`
}

// GetWorkflow returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput.Workflow, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput) GetWorkflow() *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow {
	return v.Workflow
}

// GetError returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput.Error, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutput) GetError() *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError {
	return v.Error
}

// UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError includes the requested fields of the GraphQL type MutationError.
// The GraphQL type's documentation follows.
//
// A type indicating an error has occurred while making a mutation.
type UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError struct {
	MutationErrorFields `json:"-"`
}

// GetMessage returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError.Message, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) GetMessage() string {
	return v.MutationErrorFields.Message
}

// GetType returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError.Type, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) GetType() MutationErrorType {
	return v.MutationErrorFields.Type
}

// GetCode returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError.Code, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) GetCode() string {
	return v.MutationErrorFields.Code
}

// GetFields returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError.Fields, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) GetFields() []*MutationErrorFieldsFieldsMutationFieldError {
	return v.MutationErrorFields.Fields
}

func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError
		graphql.NoUnmarshalJSON
	}
	firstPass.UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.MutationErrorFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalUpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError struct {
	Message string `json:"message"`

	Type MutationErrorType `json:"type"`

	Code string `json:"code"`

	Fields []*MutationErrorFieldsFieldsMutationFieldError `json:"fields"`
}

func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError) __premarshalJSON() (*__premarshalUpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError, error) {
	var retval __premarshalUpdateWorkflowUpdateWorkflowUpdateWorkflowOutputErrorMutationError

	retval.Message = v.MutationErrorFields.Message
	retval.Type = v.MutationErrorFields.Type
	retval.Code = v.MutationErrorFields.Code
	retval.Fields = v.MutationErrorFields.Fields
	return &retval, nil
}

// UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow includes the requested fields of the GraphQL type Workflow.
type UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow struct {
	WorkflowFields `json:"-"`
}

// GetId returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.Id, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetId() string {
	return v.WorkflowFields.Id
}

// GetName returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.Name, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetName() string {
	return v.WorkflowFields.Name
}

// GetTrigger returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.Trigger, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetTrigger() string {
	return v.WorkflowFields.Trigger
}

// GetStartStepId returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.StartStepId, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetStartStepId() *string {
	return v.WorkflowFields.StartStepId
}

// GetPublishedAt returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.PublishedAt, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetPublishedAt() *WorkflowFieldsPublishedAtDateTime {
	return v.WorkflowFields.PublishedAt
}

// GetOrder returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.Order, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetOrder() int {
	return v.WorkflowFields.Order
}

// GetSteps returns UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow.Steps, and is useful for accessing the field via an interface.
func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) GetSteps() []*WorkflowFieldsStepsWorkflowStep {
	return v.WorkflowFields.Steps
}

func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow
		graphql.NoUnmarshalJSON
	}
	firstPass.UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.WorkflowFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalUpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Trigger string `json:"trigger"`

	StartStepId *string `json:"startStepId"`

	PublishedAt *WorkflowFieldsPublishedAtDateTime `json:"publishedAt"`

	Order int `json:"order"`

	Steps []*WorkflowFieldsStepsWorkflowStep `json:"steps"`
}

func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *UpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow) __premarshalJSON() (*__premarshalUpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow, error) {
	var retval __premarshalUpdateWorkflowUpdateWorkflowUpdateWorkflowOutputWorkflow

	retval.Id = v.WorkflowFields.Id
	retval.Name = v.WorkflowFields.Name
	retval.Trigger = v.WorkflowFields.Trigger
	retval.StartStepId = v.WorkflowFields.StartStepId
	retval.PublishedAt = v.WorkflowFields.PublishedAt
	retval.Order = v.WorkflowFields.Order
	retval.Steps = v.WorkflowFields.Steps
	return &retval, nil
}

// WorkflowFields includes the GraphQL fields of Workflow requested by the fragment WorkflowFields.
type WorkflowFields struct {
	Id   string `json:"id"`
	Name string `json:"name"`
	// JSON-encoded trigger configuration, shaped as `{ "type": <triggerType>, ... }`. Valid types and their required fields:
	// - `manual` — no extra fields; the workflow runs only via the `triggerWorkflow` mutation or a UI button.
	// - `events` — `events: string[]` (at least one); runs on the listed domain events, e.g. `thread.thread_created`, `thread.message_added`, `thread.thread_field_updated`, `thread.thread_labels_changed`, `thread.thread_status_transitioned`.
	// - `schedule` — `cron: string`; runs on a recurring cron schedule evaluated in UTC.
	// Example: `{"type":"events","events":["thread.thread_field_updated"]}`.
	Trigger string `json:"trigger"`
	// The ID of the first step to execute, or null if the workflow has no steps. This cannot be cleared to null on a published workflow (`Cannot clear startStepId on a published workflow`); to restructure a published workflow's steps, unpublish it first (`updateWorkflow` with `isPublished: false`), restructure, then republish.
	StartStepId *string `json:"startStepId"`
	// Timestamp when the workflow was last published. Null means the workflow is an inactive draft.
	PublishedAt *WorkflowFieldsPublishedAtDateTime `json:"publishedAt"`
	// Display order of this workflow relative to other workflows. Lower values appear first.
	Order int `json:"order"`
	// The steps in this workflow.
	Steps []*WorkflowFieldsStepsWorkflowStep `json:"steps"`
}

// GetId returns WorkflowFields.Id, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetId() string { return v.Id }

// GetName returns WorkflowFields.Name, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetName() string { return v.Name }

// GetTrigger returns WorkflowFields.Trigger, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetTrigger() string { return v.Trigger }

// GetStartStepId returns WorkflowFields.StartStepId, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetStartStepId() *string { return v.StartStepId }

// GetPublishedAt returns WorkflowFields.PublishedAt, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetPublishedAt() *WorkflowFieldsPublishedAtDateTime { return v.PublishedAt }

// GetOrder returns WorkflowFields.Order, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetOrder() int { return v.Order }

// GetSteps returns WorkflowFields.Steps, and is useful for accessing the field via an interface.
func (v *WorkflowFields) GetSteps() []*WorkflowFieldsStepsWorkflowStep { return v.Steps }

// WorkflowFieldsPublishedAtDateTime includes the requested fields of the GraphQL type DateTime.
type WorkflowFieldsPublishedAtDateTime struct {
	Iso8601 string `json:"iso8601"`
}

// GetIso8601 returns WorkflowFieldsPublishedAtDateTime.Iso8601, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsPublishedAtDateTime) GetIso8601() string { return v.Iso8601 }

// WorkflowFieldsStepsWorkflowStep includes the requested fields of the GraphQL type WorkflowStep.
type WorkflowFieldsStepsWorkflowStep struct {
	WorkflowStepFields `json:"-"`
}

// GetId returns WorkflowFieldsStepsWorkflowStep.Id, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetId() string { return v.WorkflowStepFields.Id }

// GetWorkflowId returns WorkflowFieldsStepsWorkflowStep.WorkflowId, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetWorkflowId() string {
	return v.WorkflowStepFields.WorkflowId
}

// GetType returns WorkflowFieldsStepsWorkflowStep.Type, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetType() WorkflowStepType {
	return v.WorkflowStepFields.Type
}

// GetName returns WorkflowFieldsStepsWorkflowStep.Name, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetName() *string { return v.WorkflowStepFields.Name }

// GetPayload returns WorkflowFieldsStepsWorkflowStep.Payload, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetPayload() string { return v.WorkflowStepFields.Payload }

// GetTransitions returns WorkflowFieldsStepsWorkflowStep.Transitions, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetTransitions() []*string {
	return v.WorkflowStepFields.Transitions
}

// GetPositionX returns WorkflowFieldsStepsWorkflowStep.PositionX, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetPositionX() float64 {
	return v.WorkflowStepFields.PositionX
}

// GetPositionY returns WorkflowFieldsStepsWorkflowStep.PositionY, and is useful for accessing the field via an interface.
func (v *WorkflowFieldsStepsWorkflowStep) GetPositionY() float64 {
	return v.WorkflowStepFields.PositionY
}

func (v *WorkflowFieldsStepsWorkflowStep) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*WorkflowFieldsStepsWorkflowStep
		graphql.NoUnmarshalJSON
	}
	firstPass.WorkflowFieldsStepsWorkflowStep = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.WorkflowStepFields)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalWorkflowFieldsStepsWorkflowStep struct {
	Id string `json:"id"`

	WorkflowId string `json:"workflowId"`

	Type WorkflowStepType `json:"type"`

	Name *string `json:"name"`

	Payload string `json:"payload"`

	Transitions []*string `json:"transitions"`

	PositionX float64 `json:"positionX"`

	PositionY float64 `json:"positionY"`
}

func (v *WorkflowFieldsStepsWorkflowStep) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *WorkflowFieldsStepsWorkflowStep) __premarshalJSON() (*__premarshalWorkflowFieldsStepsWorkflowStep, error) {
	var retval __premarshalWorkflowFieldsStepsWorkflowStep

	retval.Id = v.WorkflowStepFields.Id
	retval.WorkflowId = v.WorkflowStepFields.WorkflowId
	retval.Type = v.WorkflowStepFields.Type
	retval.Name = v.WorkflowStepFields.Name
	retval.Payload = v.WorkflowStepFields.Payload
	retval.Transitions = v.WorkflowStepFields.Transitions
	retval.PositionX = v.WorkflowStepFields.PositionX
	retval.PositionY = v.WorkflowStepFields.PositionY
	return &retval, nil
}

// WorkflowStepFields includes the GraphQL fields of WorkflowStep requested by the fragment WorkflowStepFields.
type WorkflowStepFields struct {
	Id         string `json:"id"`
	WorkflowId string `json:"workflowId"`
	// The type of step: CONDITION or ACTION.
	Type WorkflowStepType `json:"type"`
	// Optional name for the step.
	Name *string `json:"name"`
	// JSON-encoded step configuration. Every payload is an object with `version: 1` and a `type` discriminator. The payload shape depends on the step `type`:
	// - CONDITION: a condition. `type` is either a leaf check (e.g. `contains_label`, `thread_field_equals`, `thread_field_is_set`, `priority_equals`, `assigned_to`, `customer_equals`, `ai_workflow_rule_condition`) or a combinator (`and`, `or`, `not`, `else_if`) that nests other conditions under `conditions`/`condition`.
	// - ACTION: an action, e.g. `apply_labels`, `remove_labels`, `set_priority`, `set_status`, `set_tier`, `assign_to_user`, `assign_to_team`, `add_note`, `send_message`, `send_slack_notification`, `send_http_request`, `set_thread_field`, `snooze_thread`, `escalate_thread`.
	// - WAIT: `{ "duration": <seconds>, "cancelCondition"?: <condition> }`.
	// Examples: `{"version":1,"type":"apply_labels","labelTypeIds":["lt_..."]}`, `{"version":1,"type":"else_if","conditions":[...]}`.
	// Payloads embed workspace-specific IDs (label type IDs, user IDs, tier IDs, etc.), which are not portable: copying a payload into another workspace references IDs that do not exist there and the step silently applies nothing.
	Payload string `json:"payload"`
	// Array of next step IDs. For ACTION: 1 element (next step). For CONDITION: 2 elements (true branch, false branch). Null means terminal/no branch.
	Transitions []*string `json:"transitions"`
	// X position of this step on the canvas.
	PositionX float64 `json:"positionX"`
	// Y position of this step on the canvas.
	PositionY float64 `json:"positionY"`
}

// GetId returns WorkflowStepFields.Id, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetId() string { return v.Id }

// GetWorkflowId returns WorkflowStepFields.WorkflowId, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetWorkflowId() string { return v.WorkflowId }

// GetType returns WorkflowStepFields.Type, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetType() WorkflowStepType { return v.Type }

// GetName returns WorkflowStepFields.Name, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetName() *string { return v.Name }

// GetPayload returns WorkflowStepFields.Payload, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetPayload() string { return v.Payload }

// GetTransitions returns WorkflowStepFields.Transitions, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetTransitions() []*string { return v.Transitions }

// GetPositionX returns WorkflowStepFields.PositionX, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetPositionX() float64 { return v.PositionX }

// GetPositionY returns WorkflowStepFields.PositionY, and is useful for accessing the field via an interface.
func (v *WorkflowStepFields) GetPositionY() float64 { return v.PositionY }

// The role a step plays in a workflow's execution graph.
type WorkflowStepType string

const (
	// Evaluates a condition; routes execution to one of two branches based on the result.
	WorkflowStepTypeCondition WorkflowStepType = "CONDITION"
	// Performs an operation such as assigning a thread, adding a label, or sending a message.
	WorkflowStepTypeAction WorkflowStepType = "ACTION"
	// Pauses execution for a configured duration, then continues to the next step.
	WorkflowStepTypeWait WorkflowStepType = "WAIT"
)

var AllWorkflowStepType = []WorkflowStepType{
	WorkflowStepTypeCondition,
	WorkflowStepTypeAction,
	WorkflowStepTypeWait,
}

// __BulkUpsertWorkflowStepsInput is used internally by genqlient
type __BulkUpsertWorkflowStepsInput struct {
	Input *BulkUpsertWorkflowStepsInput `json:"input,omitempty"`
}

// GetInput returns __BulkUpsertWorkflowStepsInput.Input, and is useful for accessing the field via an interface.
func (v *__BulkUpsertWorkflowStepsInput) GetInput() *BulkUpsertWorkflowStepsInput { return v.Input }

// __CreateWorkflowInput is used internally by genqlient
type __CreateWorkflowInput struct {
	Input *CreateWorkflowInput `json:"input,omitempty"`
}

// GetInput returns __CreateWorkflowInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateWorkflowInput) GetInput() *CreateWorkflowInput { return v.Input }

// __DeleteWorkflowInput is used internally by genqlient
type __DeleteWorkflowInput struct {
	Input *DeleteWorkflowInput `json:"input,omitempty"`
}

// GetInput returns __DeleteWorkflowInput.Input, and is useful for accessing the field via an interface.
func (v *__DeleteWorkflowInput) GetInput() *DeleteWorkflowInput { return v.Input }

// __GetWorkflowInput is used internally by genqlient
type __GetWorkflowInput struct {
	WorkflowId string `json:"workflowId"`
}

// GetWorkflowId returns __GetWorkflowInput.WorkflowId, and is useful for accessing the field via an interface.
func (v *__GetWorkflowInput) GetWorkflowId() string { return v.WorkflowId }

// __UpdateWorkflowInput is used internally by genqlient
type __UpdateWorkflowInput struct {
	Input *UpdateWorkflowInput `json:"input,omitempty"`
}

// GetInput returns __UpdateWorkflowInput.Input, and is useful for accessing the field via an interface.
func (v *__UpdateWorkflowInput) GetInput() *UpdateWorkflowInput { return v.Input }

// The mutation executed by BulkUpsertWorkflowSteps.
const BulkUpsertWorkflowSteps_Operation = `
mutation BulkUpsertWorkflowSteps ($input: BulkUpsertWorkflowStepsInput!) {
	bulkUpsertWorkflowSteps(input: $input) {
		results {
			result
			workflowStep {
				... WorkflowStepFields
			}
		}
		error {
			... MutationErrorFields
		}
	}
}
fragment WorkflowStepFields on WorkflowStep {
	id
	workflowId
	type
	name
	payload
	transitions
	positionX
	positionY
}
fragment MutationErrorFields on MutationError {
	message
	type
	code
	fields {
		field
		message
		type
	}
}
`

func BulkUpsertWorkflowSteps(
	ctx_ context.Context,
	client_ graphql.Client,
	input *BulkUpsertWorkflowStepsInput,
) (data_ *BulkUpsertWorkflowStepsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "BulkUpsertWorkflowSteps",
		Query:  BulkUpsertWorkflowSteps_Operation,
		Variables: &__BulkUpsertWorkflowStepsInput{
			Input: input,
		},
	}

	data_ = &BulkUpsertWorkflowStepsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by CreateWorkflow.
const CreateWorkflow_Operation = `
mutation CreateWorkflow ($input: CreateWorkflowInput!) {
	createWorkflow(input: $input) {
		workflow {
			... WorkflowFields
		}
		error {
			... MutationErrorFields
		}
	}
}
fragment WorkflowFields on Workflow {
	id
	name
	trigger
	startStepId
	publishedAt {
		iso8601
	}
	order
	steps {
		... WorkflowStepFields
	}
}
fragment MutationErrorFields on MutationError {
	message
	type
	code
	fields {
		field
		message
		type
	}
}
fragment WorkflowStepFields on WorkflowStep {
	id
	workflowId
	type
	name
	payload
	transitions
	positionX
	positionY
}
`

func CreateWorkflow(
	ctx_ context.Context,
	client_ graphql.Client,
	input *CreateWorkflowInput,
) (data_ *CreateWorkflowResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateWorkflow",
		Query:  CreateWorkflow_Operation,
		Variables: &__CreateWorkflowInput{
			Input: input,
		},
	}

	data_ = &CreateWorkflowResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by DeleteWorkflow.
const DeleteWorkflow_Operation = `
mutation DeleteWorkflow ($input: DeleteWorkflowInput!) {
	deleteWorkflow(input: $input) {
		error {
			... MutationErrorFields
		}
	}
}
fragment MutationErrorFields on MutationError {
	message
	type
	code
	fields {
		field
		message
		type
	}
}
`

func DeleteWorkflow(
	ctx_ context.Context,
	client_ graphql.Client,
	input *DeleteWorkflowInput,
) (data_ *DeleteWorkflowResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "DeleteWorkflow",
		Query:  DeleteWorkflow_Operation,
		Variables: &__DeleteWorkflowInput{
			Input: input,
		},
	}

	data_ = &DeleteWorkflowResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The query executed by GetWorkflow.
const GetWorkflow_Operation = `
query GetWorkflow ($workflowId: ID!) {
	workflow(workflowId: $workflowId) {
		... WorkflowFields
	}
}
fragment WorkflowFields on Workflow {
	id
	name
	trigger
	startStepId
	publishedAt {
		iso8601
	}
	order
	steps {
		... WorkflowStepFields
	}
}
fragment WorkflowStepFields on WorkflowStep {
	id
	workflowId
	type
	name
	payload
	transitions
	positionX
	positionY
}
`

func GetWorkflow(
	ctx_ context.Context,
	client_ graphql.Client,
	workflowId string,
) (data_ *GetWorkflowResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetWorkflow",
		Query:  GetWorkflow_Operation,
		Variables: &__GetWorkflowInput{
			WorkflowId: workflowId,
		},
	}

	data_ = &GetWorkflowResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}

// The mutation executed by UpdateWorkflow.
const UpdateWorkflow_Operation = `
mutation UpdateWorkflow ($input: UpdateWorkflowInput!) {
	updateWorkflow(input: $input) {
		workflow {
			... WorkflowFields
		}
		error {
			... MutationErrorFields
		}
	}
}
fragment WorkflowFields on Workflow {
	id
	name
	trigger
	startStepId
	publishedAt {
		iso8601
	}
	order
	steps {
		... WorkflowStepFields
	}
}
fragment MutationErrorFields on MutationError {
	message
	type
	code
	fields {
		field
		message
		type
	}
}
fragment WorkflowStepFields on WorkflowStep {
	id
	workflowId
	type
	name
	payload
	transitions
	positionX
	positionY
}
`

func UpdateWorkflow(
	ctx_ context.Context,
	client_ graphql.Client,
	input *UpdateWorkflowInput,
) (data_ *UpdateWorkflowResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "UpdateWorkflow",
		Query:  UpdateWorkflow_Operation,
		Variables: &__UpdateWorkflowInput{
			Input: input,
		},
	}

	data_ = &UpdateWorkflowResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
